<a href="https://colab.research.google.com/github/sowad748/Data-Mining-Assignments-/blob/main/Assignment01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [ ]:
df = pd.read_csv('heart_failure_clinical_records.csv')
df

age  anaemia  creatinine_phosphokinase  diabetes  ejection_fraction  \
0     55.0        0                       748         0                 45   
1     65.0        0                        56         0                 25   
2     45.0        0                       582         1                 38   
3     60.0        1                       754         1                 40   
4     95.0        1                       582         0                 30   
...    ...      ...                       ...       ...                ...   
4995  45.0        0                       582         1                 55   
4996  60.0        1                       582         0                 30   
4997  95.0        1                       112         0                 40   
4998  65.0        1                       160         1                 20   
4999  40.0        0                       244         0                 45   

      high_blood_pressure  platelets  serum_creatinine  serum_sodium  sex  \
0                       0  263358.03               1.3           137    1   
1                       0  305000.00               5.0           130    1   
2                       0  319000.00               0.9           140    0   
3                       1  328000.00               1.2           126    1   
4                       0  461000.00               2.0           132    1   
...                   ...        ...               ...           ...  ...   
4995                    0  543000.00               1.0           132    0   
4996                    1  127000.00               0.9           145    0   
4997                    1  196000.00               1.0           138    0   
4998                    0  327000.00               2.7           116    0   
4999                    1  275000.00               0.9           140    0   

      smoking  time  DEATH_EVENT  
0           1    88            0  
1           0   207            0  
2           0   244            0  
3           0    90            0  
4           0    50            1  
...       ...   ...          ...  
4995        0   250            0  
4996        0    95            0  
4997        0    24            1  
4998        0     8            1  
4999        0   174            0  

[5000 rows x 13 columns]

In [ ]:
df=df.iloc[:, [0,2,4,-1]]
df

age  creatinine_phosphokinase  ejection_fraction  DEATH_EVENT
0     55.0                       748                 45            0
1     65.0                        56                 25            0
2     45.0                       582                 38            0
3     60.0                       754                 40            0
4     95.0                       582                 30            1
...    ...                       ...                ...          ...
4995  45.0                       582                 55            0
4996  60.0                       582                 30            0
4997  95.0                       112                 40            1
4998  65.0                       160                 20            1
4999  40.0                       244                 45            0

[5000 rows x 4 columns]

In [ ]:
# numpy_array = df.to_numpy()
# df

# Step 1: Convert class labels to numeric values
# class_labels = df['DEATH_EVENT'].unique()  # Get unique class labels
# class_label_map = {label: index for index, label in enumerate(class_labels)}  # Map class labels to numeric values

# df['class_numeric'] = df['DEATH_EVENT'].map(class_label_map)  # Add numeric class labels to the DataFrame

# # Step 2: Store the class names in a list for future reference
# class_names = list(class_labels)

# Step 3: Convert the DataFrame to a NumPy array
# The first two columns are features and the last one is the numeric class label
data_array = df.to_numpy()

# Output
print("Data as NumPy Array:")
print(data_array)

Data as NumPy Array:
[[ 55. 748.  45.   0.]
 [ 65.  56.  25.   0.]
 [ 45. 582.  38.   0.]
 ...
 [ 95. 112.  40.   1.]
 [ 65. 160.  20.   1.]
 [ 40. 244.  45.   0.]]


In [ ]:
import pandas as pd


# Step 1: Read the CSV file into a pandas DataFrame


# Step 2: Assume the CSV has columns 'x', 'y', and 'class'
# Example: df = pd.read_csv('your_file.csv')
# Ensure that you have the relevant columns 'x', 'y', and 'class'

# Step 3: Define the marker shapes for each class
markers = { 0: 'circle', 1: 'triangle-up', 2: 'diamond'}

# Step 4: Create the figure and add scatter traces based on the class
fig = go.Figure()

for cls in df['DEATH_EVENT'].unique():
    class_df = df[df['DEATH_EVENT'] == cls] #In this line, we are using Boolean indexing to filter the original DataFrame df based on the value of cls.

    fig.add_trace(go.Scatter(
        x=class_df['age'],
        y=class_df['creatinine_phosphokinase'],
        mode='markers',
        marker=dict(symbol = markers[cls] ),   #symbol=markers.get(cls)),  # Use a default if the class is not found
        name=f'DEATH_EVENT{cls}'  # Legend label
    ))
# Add axis labels
fig.update_layout(
    xaxis_title='Age',  # Label for the x-axis
    yaxis_title='Creatinine Phosphokinase',  # Label for the y-axis
)

# Step 5: Show the plot
fig.show()

In [ ]:
markers = {0: 'circle', 1: 'cross'}  # Assign a shape to each class

# Step 3: Create a 3D scatter plot using Graph Objects
fig = go.Figure()

# Step 4: Loop through the unique classes and add them to the plot
for cls in df['DEATH_EVENT'].unique():
    class_df = df[df['DEATH_EVENT'] == cls]

    fig.add_trace(go.Scatter3d(
        x=class_df['age'],
        y=class_df['creatinine_phosphokinase'],
        z=class_df['ejection_fraction'],  # Assuming the DataFrame has a 'z' column for the third axis
        mode='markers',
        marker=dict(symbol=markers[cls], size=6),  # Use the marker shape for each class
        name=f'Class {cls}'  # Legend label for each class
    ))
# Step 5: Add axis labels
fig.update_layout(
    scene=dict(
        xaxis_title='Age',  # Label for the x-axis
        yaxis_title='Creatinine Phosphokinase',  # Label for the y-axis
        zaxis_title='Ejection Fraction'  # Label for the z-axis
    ),
)
fig.show()


In [ ]:
markers = {0: 'circle', 1: 'square'}  # Assign a shape to each class

# Step 3: Create a scatter plot using Graph Objects
fig = go.Figure()

# Step 4: Loop through the unique classes and add them to the plot
for cls in df['DEATH_EVENT'].unique():
    class_df = df[df['DEATH_EVENT'] == cls]

    # Add scatter plot for the class
    fig.add_trace(go.Scatter(
        x=class_df['age'],
        y=class_df['creatinine_phosphokinase'],
        mode='markers',
        marker=dict(symbol=markers[cls], size=6),  # Use the marker shape for each class
        name=f'Class {cls}'  # Legend label for each class
    ))

    # Step 5: Calculate the mean for each class
    mean_x = class_df['age'].mean()
    mean_y = class_df['creatinine_phosphokinase'].mean()

    # Add mean points with a larger marker size
    fig.add_trace(go.Scatter(
        x=[mean_x],
        y=[mean_y],
        mode='markers',
        marker=dict(symbol=markers[cls], size=12, color='red'),  # Same shape, larger size, red color
        name=f'Mean Class {cls}'  # Legend label for mean points
    ))
#  Add axis labels
fig.update_layout(
    xaxis_title='Age',  # Label for the x-axis
    yaxis_title='Creatinine Phosphokinase',  # Label for the y-axis
)

fig.show()

In [ ]:
# Step 3: Create a subplot figure for the histograms
fig = make_subplots(
    rows=1, cols=3,  # One row, three columns for each dimension
    subplot_titles=('Age Histogram', 'Creatinine Phosphokinase Histogram', 'Ejection Fraction Histogram')
)

# Step 4: Plot histogram for 'age'
fig.add_trace(go.Histogram(
    x=df['age'],
    nbinsx=20,  # Set number of bins
    name='Age'
), row=1, col=1)

# Step 5: Plot histogram for 'creatinine_phosphokinase'
fig.add_trace(go.Histogram(
    x=df['creatinine_phosphokinase'],
    nbinsx=20,  # Set number of bins
    name='Creatinine Phosphokinase'
), row=1, col=2)

# Step 6: Plot histogram for 'ejection_fraction'
fig.add_trace(go.Histogram(
    x=df['ejection_fraction'],
    nbinsx=20,  # Set number of bins
    name='Ejection Fraction'
), row=1, col=3)

# Step 7: Update layout to add axis titles and adjust spacing
fig.update_layout(
    title_text="Histograms of First Three Dimensions",
    showlegend=False,
    height=400,
    width=1200,
    bargap=0.1,  # Adjust gap between bars
    xaxis_title='Value',  # For the first subplot
    yaxis_title='Frequency',  # For the first subplot
    xaxis2_title='Value',  # For the second subplot
    yaxis2_title='Frequency',  # For the second subplot
    xaxis3_title='Value',  # For the third subplot
    yaxis3_title='Frequency',  # For the third subplot
)

# Step 8: Show the plot
fig.show()

In [ ]:
age_std = df['age'].std()
creatinine_phosphokinase_std = df['creatinine_phosphokinase'].std()
ejection_fraction_std = df['ejection_fraction'].std()

# Step 3: Print the results
print(f"Standard Deviation of Age: {age_std}")
print(f"Standard Deviation of Creatinine Phosphokinase: {creatinine_phosphokinase_std}")
print(f"Standard Deviation of Ejection Fraction: {ejection_fraction_std}")

Standard Deviation of Age: 11.697242810508213
Standard Deviation of Creatinine Phosphokinase: 976.7339789014968
Standard Deviation of Ejection Fraction: 11.514854806563678


In [ ]:
fig = go.Figure()

# Add box plot for 'age'
fig.add_trace(go.Box(
    y=df['age'],
    name='Age',
    boxmean=True  # Show mean line inside the box plot
))

# Add box plot for 'creatinine_phosphokinase'
fig.add_trace(go.Box(
    y=df['creatinine_phosphokinase'],
    name='Creatinine Phosphokinase',
    boxmean=True  # Show mean line inside the box plot
))

# Add box plot for 'ejection_fraction'
fig.add_trace(go.Box(
    y=df['ejection_fraction'],
    name='Ejection Fraction',
    boxmean=True  # Show mean line inside the box plot
))

# Step 3: Update layout to add axis titles
fig.update_layout(
    title="Box Plots for First Three Dimensions",
    xaxis_title="Dimension",
    yaxis_title="Values",
    showlegend=False
)

# Step 4: Show the plot
fig.show()

In [ ]:
classes = df['DEATH_EVENT'].unique() #for DEATH_EVENT=0 the class is categorized as "Survived", otherwise "Died"

# Create a box plot for each class
for cls in classes:
    class_df = df[df['DEATH_EVENT'] == cls]

    # Create a new figure for each class
    fig = go.Figure()

    # Add box plot for 'age'
    fig.add_trace(go.Box(
        y=class_df['age'],
        name='Age',
        boxmean=True  # Show mean line inside the box plot
    ))

    # Add box plot for 'creatinine_phosphokinase'
    fig.add_trace(go.Box(
        y=class_df['creatinine_phosphokinase'],
        name='Creatinine Phosphokinase',
        boxmean=True  # Show mean line inside the box plot
    ))

    # Add box plot for 'ejection_fraction'
    fig.add_trace(go.Box(
        y=class_df['ejection_fraction'],
        name='Ejection Fraction',
        boxmean=True  # Show mean line inside the box plot
    ))
    #Update layout to add axis titles
    if cls == 0:
        fig.update_layout(
            title=f"Box Plots for Survived",
            xaxis_title="Dimension",
            yaxis_title="Values",
            showlegend=False
        )
    else:
        fig.update_layout(
            title=f"Box Plots for Died",
            xaxis_title="Dimension",
            yaxis_title="Values",
            showlegend=False
        )



    # Step 5: Show the plot for each class
    fig.show()

In [ ]:
#  Select the relevant columns for the scatter matrix
dimensions = ['age', 'creatinine_phosphokinase', 'ejection_fraction']

#  Create the scatter matrix
fig = px.scatter_matrix(
    df,
    dimensions=dimensions,
    color="DEATH_EVENT",  # Color points by class (optional)
    title="3x3 Scatter Matrix of First Three Dimensions",
)

# Show the plot
fig.show()

In [ ]:
dimensions = ['age', 'creatinine_phosphokinase', 'ejection_fraction']

# Step 3: Create the parallel coordinates plot
fig = px.parallel_coordinates(
    df,
    dimensions=dimensions,
    color="DEATH_EVENT",  # Optional: Color by class (can be omitted if not needed)
    title="Parallel Coordinates for First Three Dimensions",
    labels={
        'age': 'Age',
        'creatinine_phosphokinase': 'Creatinine Phosphokinase',
        'ejection_fraction': 'Ejection Fraction',
        'DEATH_EVENT': 'Class'  # Label for the color dimension
    },
    color_continuous_scale='Viridis',  # Optional: color scale for better visualization
)

# Step 4: Show the plot
fig.show()